In [2]:
import pandas as pd
import numpy as np 
from sklearn import linear_model

In [36]:
kane = pd.read_csv('Kane.csv',sep ='\t')
rohit = pd.read_csv('rohit.csv',sep = '\t')
steve = pd.read_csv('steve.csv',sep = '\t')

In [37]:
print('Total Matches played by Kane Willimson',kane['Matches'].count())
print('Total Number of Runs scored by Kane Willimson',kane['Aggr'].max())

Total Matches played by Kane Willimson 150
Total Number of Runs scored by Kane Willimson 6154


In [43]:
print('Total Matches played by Rohit Sharma',rohit['Matches'].count())
print('Total Matches played by Rohit Sharma',rohit['Runs'].max())

Total Matches played by Rohit Sharma 224
Total Matches played by Rohit Sharma 9115


In [42]:
print('Total Matches played by Steve Smith',steve['Matches'].count())
print('Total Matches played by Steve Smith',steve['Runs'].max())

Total Matches played by Steve Smith 124
Total Matches played by Steve Smith 4148


In [44]:
kane_reg = linear_model.LinearRegression()
matches = kane[['Matches']]
runs = kane[['Aggr']]
kane_reg.fit(runs,matches)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [46]:
kane_reg.predict(18246)

427

In [47]:
import pickle

In [49]:
with open('kane_model','wb') as file:
    pickle.dump(kane_reg,file)

In [50]:
with open('kane_model','rb') as f:
    kanep = pickle.load(f)

In [51]:
kanep.predict(18246)

array([[427.76260644]])

In [53]:
rohit_reg = linear_model.LinearRegression()
matches = rohit[['Matches']]
runs = rohit[['Runs']]
rohit_reg.fit(runs,matches)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [54]:
rohit_reg.predict(18246)

array([[451.30815477]])

In [55]:
with open('rohit_model','wb') as file:
    pickle.dump(rohit_reg,file)

In [56]:
steve_reg = linear_model.LinearRegression()
matches = steve[['Matches']]
runs = steve[['Runs']]
steve_reg.fit(runs,matches)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [57]:
steve_reg.predict(18246)

array([[506.30881827]])

In [59]:
with open('steve_model','wb') as file:
    pickle.dump(steve_reg,file)